ALTER TABLE public.scholarships ADD COLUMN IF NOT EXISTS dataset_type text NOT NULL DEFAULT 'scholarship';
WITH g(school_name, program_name) AS (VALUES
('Abbotsleigh','Advanced Learning Program'),
('Aberfoyle Park High School','IGNITE program'),
('Aetaomah School','Aetaomah School Scholarship Programmeproviding Equity in Steiner Education'),
('Ajuga School','Inspire - High potential and gifted education (HPGE)'),
('Al Zahra College','Scholarships'),
('Al-Faisal College','Awards and Scholarships'),
('Al-Faisal College - Campbelltown','Awards and Scholarships'),
('Al-Faisal College - Lakemba','Awards and Scholarships'),
('Al-Faisal College - Liverpool','Awards and Scholarships'),
('Alexandra Hills TAFE Senior Studies Program','Selective/Gifted Entry Program'),
('Alexandria Park Community School','Inspire - High potential and gifted education'),
('All Saints Grammar','Scholarships'),
('All Saints Grammar Junior School','Scholarships'),
('Anglican Church Grammar School','Scholarships'),
('Arden Anglican School','SCHOLARSHIPS'),
('Arden Anglican School, Junior Campus','SCHOLARSHIPS'),
('Arndell School','Inspire - High potential and gifted education'),
('Arrahman College','Scholarships and Bursaries'),
('Assumption College','Faith & Enrichment'),
('Auburn High School','SEAL Program'),
('Aurora College','High Potential and Gifted Education (HPGE) Program'),
('Australian International Academy, Kellyville Campus','Types of Scholarships'),
('Australian International Academy, Sydney, Strathfield Campus','Types of Scholarships'),
('Bacchus Marsh Grammar - Maddingley Campus','Selective/Gifted Entry Program'),
('Balgowlah Heights Public School','High potential and gifted education'),
('Ballarat Christian College','2027 Scholarships'),
('Barker College','Gifted Education'),
('Barker College Junior School','Gifted Education'),
('Bathurst High School','Selective High School Entry Program'),
('Baulkham Hills High School','Selective High School Entry Program'),
('Bayview College','Year 7 Scholarships and Bursaries'),
('Beaudesert State High School','Excellence Program'),
('Bellarine Secondary College','Advanced Learning Program'),
('Bellarine Secondary College-Ocean Grove Campus','Advanced Learning Program'),
('Bellbird Park State Secondary College','Excellence Program'),
('Belmont City College','Excellence Program'),
('Bethany Catholic Primary School','Gifted and Talented Enrichment Program'),
('Bishop Tyrrell Anglican College','Identifying high Potential learners'),
('Blacktown Girls High School','Selective High School Entry Program'),
('Bob Hawke College','Selective Entry Program'),
('Brentwood Secondary College','Select Entry Accelerated Learning (SEAL) Program'),
('Brighton Grammar School','Scholarships'),
('Brigidine College','Scholarships'),
('Broome Senior High School','Pathways Program'),
('Broughton Anglican College','Scholarships'),
('Budawang School','Inspire – High potential and gifted education'),
('Bullimbal School','Inspire – High potential and gifted education'),
('Bunbury Catholic College','2027 Scholarships, Bursaries and Elite Sports Applications'),
('Burgmann Anglican School','Selective/Gifted Entry Program'),
('Burgmann Anglican School - Forde Campus','Selective/Gifted Entry Program'),
('Butler College','Academic Extension Program'),
('Cairnsfoot School','Inspire – High potential and gifted education (HPGE)'),
('Caldera School','Inspire – High potential and gifted education'),
('Calvin Christian School','OJ Hofman Scholarships'),
('Calvin Christian School - Secondary Campus','OJ Hofman Scholarships'),
('Camberwell Girls Grammar School','Gifted and Talented Program'),
('Camberwell Girls Grammar School - Junior Campus','Gifted and Talented Program'),
('Camberwell High School','Select Entry Accelerated Learning (SEAL) Program'),
('Canberra Girls Grammar School','Academic Enrichment'),
('Canberra Girls Grammar School - Junior School','Academic Enrichment'),
('Cannon Hill Anglican College','Scholarships'),
('Canterbury College','Scholarships'),
('Canterbury Girls Secondary College','Select Entry Accelerated Learning (SEAL) Program'),
('Carenne School','Inspire – High potential and gifted education'),
('Carey Baptist Grammar School - Donvale Campus','Scholarships'),
('Caringbah High School','Selective High School Entry Program'),
('Carinya School','Inspire – High potential and gifted education'),
('Carmel School','Carmel Scholarship Program'),
('Caroline Chisholm Catholic College','Aspire Program'),
('Caroline Chisholm Catholic College - Christ the King Campus','Aspire Program'),
('Caroline Chisholm Catholic College - Sacred Heart Campus','Aspire Program'),
('Casuarina School','Inspire – High potential and gifted education'),
('Catherine McAuley Westmead','Year 9 Talented Mathematics Students Workshop'),
('Caulfield Grammar School','Scholarships'),
('Central Coast Steiner School','Scholarships'),
('Central West Leadership Academy','Selective/Gifted Entry Program'),
('Chatswood High School','Selective High School Entry Program'),
('Chevalier College','Selective/Gifted Entry Program'),
('Christ Church Grammar School Perth','Gifted and Talented Program'),
('Christ the King Catholic Primary School Bass Hill','2026 CEF Teaching Scholarship recipients welcomed into SCS community'),
('Christian Brothers College - Junior Campus','Gifted & Talented'),
('Christian Brothers'' High School Lewisham','ACE Program (Academic Challenge & Enrichment)'),
('Christway College','Scholarship Program - 2027'),
('Claremont College','Gifted and Talented Programs at Claremont'),
('Clarence Valley Anglican School','Scholarships'),
('Clayfield College','Scholarship Program'),
('Coleambally Central School','Inspire – High potential and gifted education'),
('Colyton High School','Inspire – High potential and gifted education'),
('Concordia Lutheran College','Scholarships'),
('Concordia Lutheran College - Concordia Primary Campus','Scholarships'),
('Concordia Lutheran College - Martin Luther Primary Campus','Scholarships'),
('Cook School','Inspire – High potential and gifted education'),
('Coombabah State High School','Excellence Program'),
('Coomera Anglican College','Scholarships'),
('Coreen School','Inspire – High potential and gifted education'),
('Cornish College','Scholarships'),
('Corpus Christi College','Gifted and Talented Program'),
('Craigslea State High School','Excellence Program'),
('Cranbrook Junior School','Scholarships'),
('Cranbrook School','Scholarships'),
('Cromehurst School','Inspire – High potential and gifted education'),
('Croxton School','Advanced Learning Program'),
('Dalby State High School','Futures Program'),
('Dalby State High School - Bunya Campus','Futures Program'),
('Danebank - An Anglican School for Girls','Scholarships'),
('Daramalan College','Gifted and Talented'),
('Darkinjung Barker','Gifted Education'),
('Dorchester School','Inspire – High potential and gifted education'),
('EOC Broken Bay - Narraweena','Gifted and Talented'),
('ET Australia Secondary College','Gifted & TalentedProgram'),
('ET Australia Secondary College Senior Campus','Gifted & TalentedProgram'),
('Eagle Vale High School','Inspire – High potential and gifted education'),
('Edgeware School','Inspire – High potential and gifted education'),
('Edinburgh College','Selective/Gifted Entry Program'),
('Edmund Rice College','Enrichment'),
('Eltham College','Pathways Program'),
('Eltham College - Lonsdale Street Campus','Pathways Program'),
('Emmanuel Catholic College','Gifted and Talented Program'),
('Emmanuel Christian School','OJ Hofman Scholarships'),
('Endeavour College','Scholarships'),
('Erasmus Primary School','2027 Scholarships'),
('Fahan School','Scholarships'),
('Fairholme College','Scholarships'),
('Faith Lutheran College - Plainland','Scholarships'),
('Farrer Memorial Agricultural High School','High Potential and Gifted Education (HPGE)'),
('Fernhill School','Inspire – High potential and gifted education'),
('Fintona Girls'' School','Scholarships'),
('Fort Street High School','Inspire – High potential and gifted education'),
('Foxwell State Secondary College','Excellence Program'),
('Frensham School','Scholarships and Bursaries'),
('Freshwater Christian College','High Ability & High Performance'),
('Galston High School','High potential and gifted education'),
('Geelong Lutheran College - Armstrong Creek Campus','Scholarships'),
('Geelong Lutheran College - St John''s Newtown Campus','Scholarships'),
('Georges River Grammar','Ability Scholarships'),
('Georgiana Molloy Anglican School','PEAK Program'),
('Girrakool School','Inspire – High potential and gifted education'),
('Girraween High School','Selective High School Entry Program'),
('Girton Grammar School','Excellence Program'),
('Girton Grammar School - Junior School','Excellence Program'),
('Gladstone Park Secondary College','SEAL – Select Entry Accelerated Learning'),
('Glen Eira College','SEAL Program'),
('Glen Innes High School','Selective High School Entry Program'),
('Glenvale School','Inspire – High potential and gifted education'),
('Good Shepherd Lutheran College','Gifted and Talented Program'),
('Gosford High School','Gosford High School'),
('Goulburn High School','Inspire – High potential and gifted education'),
('Goulburn Valley Grammar School','Scholarships'),
('Gralee School','Inspire – High potential and gifted education'),
('Greenwood College','Elite Academic Program'),
('Gymea Technology High School','Inspire – High potential and gifted education at Gymea Technology'),
('Haileybury College - Pangea','Gifted and Talented Program'),
('Hale School','Selective/Gifted Entry Program'),
('Hale School Perth','Academic Extension and Enrichment Program'),
('Halinda School','Inspire – High potential and gifted education'),
('Hartford College','Scholarships and Bursaries'),
('Havenlee School','Inspire – High potential and gifted education'),
('Highlands School','Inspire – High potential and gifted education'),
('Hillcrest Christian College','Scholarships & Awards'),
('Hillcrest Christian College - Coolangatta Campus','Gifted and Talented Program'),
('Holroyd School','Inspire – High potential and gifted education'),
('HopeTown School','Inspire – High potential and gifted education'),
('Hornsby Girls High School','Selective High School Entry Program'),
('Horsham College','SEAL Program'),
('Horsham College-Baillie Street Campus','SEAL Program'),
('Horsham College-Mc Kenzie Creek Campus','SEAL Program'),
('Hume Anglican Grammar - Donnybrook Campus','Gifted and Talented Program'),
('Hunter Christian School','Scholarships'),
('Hunter School of Performing Arts','Inspire - High potential and gifted education'),
('Hunter Valley Grammar School','What scholarships do you offer?'),
('Hunter Valley Grammar School - Farm','What scholarships do you offer?'),
('Hurlstone Agricultural High School','Selective Agricultural High School Entry Program'),
('Inaburra School','Scholarships at Inaburra'),
('Induna School','Inspire – High potential and gifted education'),
('International Grammar School','The Indigenous Scholarship Program'),
('International Maarif Schools of Australia - Auburn Campus','Available Scholarships'),
('International School of Western Australia','Scholarships'),
('Investigator College','Scholarships'),
('Iona College','ACE Program (Academic Challenge & Enrichment)'),
('Islamic College of Sport','Elite Academic Program'),
('Islamic College of Sport - Hoppers Crossing Campus','Elite Academic Program'),
('Islamic College of Sport NSW','Elite Academic Program'),
('Ivanhoe Girls'' Grammar School','EnrolScholarships'),
('James Ruse Agricultural High School','James RuseAgricultural High School'),
('John Curtin College Of The Arts','Gifted and Talented Programs'),
('John Monash Science School','Select Entry Accelerated Learning Program'),
('John Therry Catholic College','The John Therry Gifted & Talented Program'),
('John XXIII College','∨ Does John XXIII College offer scholarships?'),
('Kalinda School','Inspire – High potential and gifted education'),
('Kandeer School','Inspire – High potential and gifted education'),
('Karningul School','Inspire – High potential and gifted education'),
('Karonga School','High potential and gifted education'),
('Kawana Waters State College','Excellence Program'),
('Keilor Downs College','Select Entry Accelerated Learning (SEAL) Program'),
('Keilor Downs Secondary College','SEAL Select Entry & Accelerated Learning'),
('Kelmscott Senior High School','Gifted and Talented Program'),
('Kennedy Baptist College','Selective/Gifted Entry Program'),
('Kilbreda College','Accelerated Studies'),
('Kildare College','Enrichment'),
('King''s Christian College','Scholarships'),
('King''s Christian College - Chambers Flat Campus','Scholarships'),
('King''s Christian College - Pimpama Campus','Scholarships'),
('King''s College','Scholarships and Bursaries'),
('Kingdom Culture Christian School','Scholarships'),
('Kingsley College','2027 Scholarships'),
('Kingsway Christian College','Gifted and Talented Programme'),
('Kingswood College','Gifted and Talented Program'),
('Kinross College','Academic Extension Program'),
('Knox Grammar Preparatory School','Scholarships'),
('Kolbe Catholic College','Gifted and Talented Program'),
('Koo Wee Rup Secondary College','HAP – High Ability Program'),
('Korowa Anglican Girls'' School','Enrichmentand Extension'),
('Korowal School','Scholarships'),
('Kotara School','Inspire – High potential and gifted education'),
('Kurrambee School','What is Inspire - High potential and gifted education?'),
('La Salle Catholic College','2026 CEF Teaching Scholarship recipients welcomed into SCS community'),
('Lakes Grammar - An Anglican School','Enrichment, Extension and Acceleration'),
('Lakeside School','Inspire – High potential and gifted education'),
('Lauriston Girls'' School','Scholarships'),
('Lauriston Girls'' School - Howqua Campus','Scholarships'),
('Le Page Primary School','Born to Soar – Gifted and Talented Education'),
('Leibler Yavneh College','Scholarships'),
('Lesmurdie Senior High School','Scholarships'),
('Lincoln School','Inspire – High potential and gifted education'),
('Lindisfarne Anglican Grammar School','Scholarships'),
('Lindisfarne Anglican Grammar School, Junior School','Scholarships'),
('Living School','Scholarship Criterion at Living School'),
('Living School - Southern Cross University Campus','Scholarship Criterion at Living School'),
('Living Waters Lutheran College','ACADEMIC SCHOLARSHIP INFORMATION'),
('Loreto College','Scholarships'),
('Loreto College Coorparoo','Scholarships'),
('Loreto Kirribilli','Gifted Education'),
('Loreto Mandeville Hall','Scholarships'),
('Lowther Hall Anglican Grammar School','Scholarships'),
('Lumen Christi College','Selective/Gifted Entry Program'),
('Luther College','Scholarships'),
('Lyndale Secondary College','Advanced Challenge and Enrichment (ACE) Program'),
('MLC School Perth','Gifted and Talented Program'),
('MacRobertson Girls High School','Select Entry Accelerated Learning Program'),
('Macarthur Adventist College','Gifted and Talented Program'),
('Macarthur Anglican School','Gifted and Talented Program'),
('Mackay State High School','Excellence Program'),
('Macksville High School','Inspire – High potential and gifted education (HPGE)'),
('Macquarie Anglican Grammar School','Fees & Scholarships'),
('Maharishi School of the Age of Enlightenment','SCHOLARSHIPS'),
('Mamre Anglican School','Scholarship Opportunities'),
('Maranatha Christian School','Scholarship'),
('Maranatha Christian School - Officer Campus','Scholarship'),
('Marcellin College','Gifted and Talented Program'),
('Marian Catholic College','GIFTED AND TALENTED'),
('Marymede Catholic College','Selective/Gifted Entry Program'),
('Marymede Catholic College - Doreen','Selective/Gifted Entry Program'),
('Melbourne Girls Grammar','SCHOLARSHIPS'),
('Melbourne High School','Select Entry Accelerated Learning Program'),
('Mentone Grammar School','ENRICHMENT PROGRAMS'),
('Mercedes College','Scholarships'),
('Merici College','Gifted and Talented Students'),
('Mernda Hills Christian College','Scholarships'),
('Methodist Ladies'' College - Mallacoota Campus','Learning Support and Enrichment'),
('Mian School','High potential and gifted education'),
('Mill Park Secondary College','SEAL/Accelerated Learning Programs'),
('Mill Park Secondary College-Senior Campus','SEAL/Accelerated Learning Programs'),
('Minerva School','High potential and gifted education'),
('Montgrove College','Scholarships'),
('Morley Senior High School','Gifted and Talented Program'),
('Mount Alvernia College','Scholarships'),
('Mount Barker Community College','Academic Extension Program'),
('Mt Hira College','2027 Scholarships'),
('Nambour State College','Excellence Program'),
('Nambour State College - Junior School','Excellence Program'),
('Narara Valley High School','High potential and gifted education'),
('Naremburn School','Inspire – High potential and gifted education'),
('Navigator College','Scholarships'),
('Nazareth College','Extension, Acceleration and Enrichment'),
('Nazareth School','Extension, Acceleration and Enrichment'),
('Newington College','Scholarships'),
('Newington College - Lindfield Preparatory School','Scholarships'),
('Newington College - Wyvern House Preparatory School','Scholarships'),
('Newman College','Gifted & Talented'),
('Niland School','Inspire – High potential and gifted education'),
('Normanhurst Boys High School','Selective High School Entry Program'),
('North Rockhampton State High School','Excellence Program'),
('North Sydney Boys High School','Welcome to North Sydney Boys High School'),
('North Sydney Girls High School','Selective Entry Program'),
('Northcote High School','ACE Program'),
('Northholm Grammar School','Gifted and Talented Program'),
('Northshore Christian Grammar School','Scholarships'),
('Nossal High School','Select Entry Accelerated Learning Program'),
('Oak Flats High School','Inspire – High potential and gifted education (HPGE)'),
('Oakbank School','Venture Program'),
('Ormeau Woods State High School','Excellence Program'),
('Ormiston College','Scholarships'),
('Our Lady of Fatima Catholic Primary School','Gifted program part of the plot in storytelling win'),
('Our Lady of Mercy College','Scholarships and Bursaries'),
('Our Lady''s College','Compass Program'),
('Oxley College','Scholarships'),
('PLC Armidale','Scholarships and Bursaries'),
('Pacific Lutheran College','Scholarships and Bursaries'),
('Pal Buddhist School','Our Scholarship Program'),
('Parkerville Steiner College','Scholarships'),
('Pedare Christian College','Scholarships'),
('Pembroke School - Junior School Campus','Gifted and Talented Program'),
('Penrhos College','Scholarships'),
('Penrith High School','Penrith Selective High School'),
('Peregian Beach College','Gifted and Talented Program'),
('Perth Modern School','Selective Entry Program'),
('Pioneer State High School','Excellence Program'),
('Pittwater House Schools','Scholarships'),
('Playford College','Scholarships'),
('Presbyterian Ladies College Perth','Gifted and Talented Program'),
('Prescott College Southern','Scholarship and Bursaries'),
('Putland School','High potential and gifted education'),
('Queensland Academy for Creative Industries','Gifted and Talented Program'),
('Queenwood','Gifted and Talented Program'),
('Queenwood Junior School','Gifted and Talented Program'),
('Redbank School','Inspire – High potential and gifted education'),
('Reddam House','Scholars Program'),
('Reddam House North Shore','Scholars Program'),
('Reddam House, Bondi Campus','Scholars Program'),
('Redfield College','Scholarships'),
('Redlands College','Accelerated Reader Hall of Fame'),
('Regents Park Christian School','Gifted and Talented'),
('Reservoir High School','SEAL 2026'),
('Reservoir High School-Heidelberg Secondary Teaching Unit','SEAL 2026'),
('Ringwood Secondary College','Selective/Gifted Entry Program'),
('Rivendell School','Inspire – High potential and gifted education'),
('Riverside Christian College','Scholarships & Bursaries'),
('Riverside Christian College - Subcampus','Scholarships & Bursaries'),
('Rockhampton Girls Grammar School','SCHOLARSHIPS'),
('Rosebank College','Scholarships'),
('Rossmoyne Senior High School','Gifted and Talented Program'),
('Rouse Hill Anglican College','Scholarships'),
('Runcorn State High School','Horizons Program'),
('SEDA College (Victoria)','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - AFL - Clayton','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - AFL - Sunshine','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - AFL - Werribee','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - AFL Traralgon & Multi 2 Traralgon','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - AFL Victoria & Cricket Australia Sports Development Program - Strathmore','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - AFL- Geelong','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - AFL- Preston','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - BVNV Geelong','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Basketball Braybrook','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Basketball Broadmeadows','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Basketball Burwood','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Brens Pavilion Royal Park','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Cricket Australia - Box Hill','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Cricket Australia - Footscray','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - FFV Burnley','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - FFV Burnley 2','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Flemington HUB','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Frankston Park Function Centre','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Hawthorn Talented Player Program (TPP)','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Jubilee Park','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - MSAC Function Room','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Melbourne City Talented Player Program - Kensington','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Melbourne Sports Centres Parkville','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Multi Ballarat','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Multi Sports - Shepparton','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Netball - Keysborough','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Netball Ascot Vale','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Netball Burnley','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Ryans Reserve Tennis & Netball Centre','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - Sailing - Albert Park','Sports Education and Development Australia (SEDA) Program'),
('SEDA College (Victoria) - The Huddle, North Melbourne Football Club','Sports Education and Development Australia (SEDA) Program'),
('Sacre Coeur','Scholarships'),
('Sacred Heart School','Scholarships'),
('Saint Ignatius College Geelong','Scholarship Applications are Now Open'),
('Saint Ignatius'' College','Selective/Gifted Entry Program'),
('Saint Ignatius'' College - Junior School Campus','Gifted and Talented Program'),
('Saint Ignatius'' College - Senior School Campus','Gifted and Talented Program'),
('Saint Ignatius'' College, The Regis Campus','Selective/Gifted Entry Program'),
('Salesian College Chadstone','EnrichmentPrograms'),
('Salvado Catholic College','Scholarships'),
('Sandgate District State High School','Excellence Program'),
('Santa Sophia Catholic College (Primary)','Accelerated Science students extract DNA with microbiologists'),
('Sapphire Coast Anglican College','Scholarships'),
('Sarina State High School','Excellence Program'),
('Scots All Saints College','Apply for a Scots All Saints College Scholarship'),
('Scots All Saints College, Campus West','Apply for a Scots All Saints College ScholarshipÂ'),
('Servite College','Gifted Education at Servite'),
('Sheldon College','Learning Enrichment'),
('Shellharbour Anglican College','Scholarships'),
('Shenton College','Gifted and Talented Applications for 2024 Closing Soon'),
('Sirius College','Selective/Gifted Entry Program'),
('Sirius College - Dallas Campus','Selective/Gifted Entry Program'),
('Sirius College - Geelong Campus','Selective/Gifted Entry Program'),
('Sirius College - Ibrahim Dellal Campus','Selective/Gifted Entry Program'),
('Sirius College - Keysborough Campus','Selective/Gifted Entry Program'),
('Somerville House','Scholarships & Bursaries'),
('South Coast Baptist College','Gifted & Talented'),
('Southern Cross Grammar','Scholarships'),
('Southern Highlands Christian School','Scholarships'),
('Southern Vales Christian College - Aldinga Campus','Scholarship Opportunities'),
('Southern Vales Christian College - Morphett Vale Campus','Scholarship Opportunities'),
('Springfield Central State High School','Excellence Program'),
('St Agnes Catholic High School','Gifted and talented program'),
('St Albans Secondary College-Strathbogie Camp','SEAL & Accelerated Learning Program'),
('St Andrew''s Grammar','Selective/Gifted Entry Program'),
('St Augustine''s College','Selective/Gifted Entry Program'),
('St Columba Anglican School','Scholarships on Offer'),
('St Columba College','Academic Extension Program'),
('St Columba''s College','SCHOLARSHIPS'),
('St Dominic''s College','Ignite Program'),
('St Euphemia College','Academic Scholarships 2026'),
('St George Christian School','Gifted and Talented Program'),
('St George Christian School (Infants)','Gifted and Talented Program'),
('St George College - Junior Campus','Academic Scholarships(Non-Current Students can apply)'),
('St George College - Senior Campus','Academic Scholarships(Non-Current Students can apply)'),
('St James'' Anglican School','Learning Support & Extension'),
('St John''s College Preston','Gifted and Talented Program'),
('St Joseph''s Catholic Primary School Como - Oyster Bay','2026 CEF Teaching Scholarship recipients welcomed into SCS community'),
('St Joseph''s College','Selective/Gifted Entry Program'),
('St Joseph''s College - Waterford Place Campus','Selective/Gifted Entry Program'),
('St Joseph''s Nudgee College','Scholarships'),
('St Luke''s Grammar School','Selective/Gifted Entry Program'),
('St Luke''s Grammar School, Bayview Campus','Selective/Gifted Entry Program'),
('St Margaret''s Berwick Grammar','Scholarships'),
('St Margaret''s Berwick Grammar - Berwick Grammar School','Scholarships'),
('St Mary MacKillop Primary School','Gifted and Talented Program'),
('St Patrick''s College, Strathfield','F Gleeson Gifted Education Program'),
('St Paul''s Grammar School','Scholarships'),
('St Paul''s School','Scholarships'),
('St Peter''s Anglican College - Broulee','Scholarship Program'),
('St Peter''s Woodlands Grammar School','Gifted and Talented Program'),
('St Raphael''s School','Accelerate Program'),
('St Rita''s College','What support and extension opportunities are available at the College?'),
('St Scholastica''s College Glebe Point','EXTENSION and ENRICHMENT OPPORTUNITIES'),
('St Spyridon College','Scholarship opportunities for new and existing students:'),
('St Stephen''s School','Gifted and talented teacher'),
('St Stephen''s School - Carramar Campus','Gifted and talented teacher'),
('St Stephen''s School - Early Learning Centre','Gifted and talented teacher'),
('St Thomas Aquinas College','Scholarship Program'),
('Star of the Sea College','Gifted and Talented Program'),
('Strathcona Baptist Girls'' Grammar','Scholarships'),
('Strathcona Baptist Girls'' Grammar - Hawthorn Campus','Scholarships'),
('Strathcona Baptist Girls'' Grammar - Primary Campus','Scholarships'),
('Strathfield Girls High School','High potential and gifted education'),
('Sunshine Coast Grammar School','SCHOLARSHIPS'),
('Sunshine College','Scholarships'),
('Sunshine College-North Sunshine Campus','Scholarships'),
('Suzanne Cory High School','Select Entry Accelerated Learning Program'),
('Swan Hill College','Gifted and Talented Program'),
('Swan Hill College-FLO Campus','Gifted and Talented Program'),
('Sydney Adventist School - Auburn','Gifted and Talented Program'),
('Sydney Girls High School','Gifted and Talented Program'),
('Sydney Secondary College Balmain Campus','Inspire – High potential and gifted education'),
('Tallowood School','Inspire – High potential and gifted education'),
('Taminmin College','Compass Program'),
('Tangara School','Inspire – High potential and gifted education'),
('Tangara School for Girls','Scholarships'),
('Tatachilla Lutheran College','Learning extension'),
('Tempe High School','High potential and gifted education at Tempe High School'),
('The Essington School','Gifted and Talented Program'),
('The Friends'' School','Enrichment'),
('The Friends'' School - Argyle Street Campus','Enrichment'),
('The Hills Grammar School','Gifted and Talented Program'),
('The King''s College','Gifted and Talented'),
('The King''s School','Scholarships and Bursaries'),
('The King''s School, Tudor House','Gifted and Talented Program'),
('The Knox School','Scholarships'),
('The SCOTS PGC College','Scholarship Fund'),
('The SCOTS PGC College - Lock Street Campus','Scholarship Fund'),
('The Scots College','Scholarships and Bursaries'),
('The Springfield Anglican College','Scholarships'),
('The Springfield Anglican College - Primary Campus','Scholarships'),
('Thomas Hassall Anglican College','Scholarship Program'),
('Tintern Grammar','Scholarships'),
('Toodyay District High School','Pathways Program'),
('Toormina Public School','Inspire – High potential and gifted education'),
('Townsville Grammar School','Townsville Grammar''s Enrichment Programs for Gifted Students'),
('Townsville Grammar School - Annandale Campus','Townsville Grammar''s Enrichment Programs for Gifted Students'),
('Townsville Grammar School - Burdell Campus','Townsville Grammar''s Enrichment Programs for Gifted Students'),
('Tranby College','Our Gifted and Talented Program'),
('Trinity Anglican School','Excellence Program'),
('Trinity Anglican School - Marlin Coast Campus','Excellence Program'),
('Trinity College','Excellence Program'),
('Trinity Grammar School','Extension, Enrichment and Support'),
('Trinity Grammar School Bishop Chambers House','Extension, Enrichment and Support'),
('Trinity Grammar School Field Studies Centre, Woollamia Campus','Extension, Enrichment and Support'),
('Trinity Grammar School Preparatory School','Extension, Enrichment and Support'),
('Upper Coomera State College','Pathways Program'),
('Urangan State High School','ACE & Scholarship'),
('Verona School','Inspire – High potential and gifted education'),
('Viewbank College','Pathways Program'),
('Wairoa School','Inspire – High potential and gifted education (HPGE)'),
('Wakefield School','Higher potential and gifted education'),
('Wangaratta High School','Select Entry Accelerated Learning (SEAL) Program'),
('Warrnambool College','SEAL Program'),
('Warrnambool College-Wave Campus','SEAL Program'),
('Waverley Christian College - Narre Warren South Campus','Enrichment'),
('Wesley College','Gifted & Talented'),
('West Moreton Anglican College','Selective/Gifted Entry Program'),
('Westbourne College Sydney','Do you offer scholarships?'),
('Westbourne College Sydney - Macarthur St','Do you offer scholarships?'),
('Westbourne Grammar School','Student Learning Accelerated 2022'),
('Westbourne Grammar School - Williamstown Campus','Student Learning Accelerated 2022'),
('Western Australian College Of Agriculture - Denmark','Scholarships'),
('Westfields Sports High School','Sports Selective Entry Program'),
('Whitefriars College','Gifted and Talented Program'),
('Whitsunday Anglican School','Scholarships'),
('Willetton Senior High School','Gifted and Talented'),
('William Carey Christian School','Advanced Learning'),
('William Ross State High School','Excellence Program'),
('Williamstown High School','Select Entry Accelerated Learning (SEAL) Program'),
('Wisdom College','ENRICHMENT'),
('Wodonga Middle Years College','Gifted and Talented Program'),
('Wodonga Middle Years College-Felltimber Campus','Gifted and Talented Program'),
('Wodonga Middle Years College-Flying Fruit Fly Circus School','Gifted and Talented Program'),
('Wodonga Middle Years College-HighWater Campus','Gifted and Talented Program'),
('Wollemi College','Scholarships'),
('Woodcroft College','SCHOLARSHIPS'),
('Woodridge State High School','Excellence Program'),
('Xavier College - Burke Hall','2027 Scholarships (Applications Now Closed)'),
('Xavier College - Kostka Hall','2027 Scholarships (Applications Now Closed)')
)
UPDATE public.scholarships s SET dataset_type='gifted_program'
FROM g WHERE s.school_name=g.school_name AND s.program_name=g.program_name;