DROP TRIGGER IF EXISTS admin_profiles_touch_updated_at ON public.admin_profiles;
DROP TABLE IF EXISTS public.admin_profiles;

INSERT INTO public.profiles (
  id,
  email,
  full_name,
  state,
  postcode,
  suburb,
  year_level,
  school_type,
  grades,
  extracurriculars,
  financial_need,
  target_year,
  target_schools,
  scholarship_categories,
  view_mode,
  streak_days,
  streak_label,
  last_name,
  gender,
  parent_email,
  current_school_name,
  current_school_type,
  is_indigenous,
  is_rural,
  faith_background,
  preferred_sectors,
  willing_to_board,
  max_travel_km,
  has_sibling_enrolled,
  target_start_year,
  applying_year_level,
  dream_schools,
  onboarding_completed
)
SELECT
  u.id,
  u.email,
  COALESCE(NULLIF(u.raw_user_meta_data->>'full_name', ''), NULLIF(u.raw_user_meta_data->>'name', ''), split_part(u.email, '@', 1)),
  COALESCE(NULLIF(u.raw_user_meta_data->>'state', ''), 'NSW'),
  COALESCE(NULLIF(u.raw_user_meta_data->>'postcode', ''), '0000'),
  NULLIF(u.raw_user_meta_data->>'suburb', ''),
  NULLIF(u.raw_user_meta_data->>'year_level', ''),
  NULLIF(u.raw_user_meta_data->>'school_type', ''),
  '{}'::jsonb,
  COALESCE(ARRAY(SELECT jsonb_array_elements_text(COALESCE(u.raw_user_meta_data->'extracurriculars', '[]'::jsonb))), '{}'::text[]),
  NULLIF(u.raw_user_meta_data->>'financial_need', ''),
  NULLIF(u.raw_user_meta_data->>'target_year', ''),
  COALESCE(ARRAY(SELECT jsonb_array_elements_text(COALESCE(u.raw_user_meta_data->'target_schools', '[]'::jsonb))), '{}'::text[]),
  COALESCE(ARRAY(SELECT jsonb_array_elements_text(COALESCE(u.raw_user_meta_data->'scholarship_categories', u.raw_user_meta_data->'interests', '[]'::jsonb))), '{}'::text[]),
  'student',
  1,
  'Fire Band',
  NULLIF(u.raw_user_meta_data->>'last_name', ''),
  NULLIF(u.raw_user_meta_data->>'gender', ''),
  NULLIF(u.raw_user_meta_data->>'parent_email', ''),
  NULLIF(u.raw_user_meta_data->>'current_school_name', ''),
  NULLIF(u.raw_user_meta_data->>'current_school_type', ''),
  COALESCE(NULLIF(u.raw_user_meta_data->>'is_indigenous', '')::boolean, false),
  COALESCE(NULLIF(u.raw_user_meta_data->>'is_rural', '')::boolean, false),
  NULLIF(u.raw_user_meta_data->>'faith_background', ''),
  COALESCE(ARRAY(SELECT jsonb_array_elements_text(COALESCE(u.raw_user_meta_data->'preferred_sectors', '[]'::jsonb))), '{}'::text[]),
  NULLIF(u.raw_user_meta_data->>'willing_to_board', ''),
  COALESCE(NULLIF(u.raw_user_meta_data->>'max_travel_km', '')::integer, 999),
  COALESCE(NULLIF(u.raw_user_meta_data->>'has_sibling_enrolled', '')::boolean, false),
  NULLIF(u.raw_user_meta_data->>'target_start_year', '')::integer,
  NULLIF(u.raw_user_meta_data->>'applying_year_level', '')::integer,
  NULLIF(u.raw_user_meta_data->>'dream_schools', ''),
  COALESCE(NULLIF(u.raw_user_meta_data->>'onboarding_completed', '')::boolean, false)
FROM auth.users u
LEFT JOIN public.profiles p ON p.id = u.id
WHERE p.id IS NULL
ON CONFLICT (id) DO NOTHING;